#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
#
Name     : dotconf
Version  : 1.3
Release  : 1
URL      : https://github.com/williamh/dotconf/archive/refs/tags/v1.3.tar.gz
Source0  : https://github.com/williamh/dotconf/archive/refs/tags/v1.3.tar.gz
Summary  : config file parser
Group    : Development/Tools
License  : LGPL-2.1
Requires: dotconf-lib = %{version}-%{release}
Requires: dotconf-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
dot.conf v1.3
This file lists changes that break backward compatibility with previous
versions.  Please see the files in the doc directory of the distribution for
full details.

%package dev
Summary: dev components for the dotconf package.
Group: Development
Requires: dotconf-lib = %{version}-%{release}
Provides: dotconf-devel = %{version}-%{release}
Requires: dotconf = %{version}-%{release}

%description dev
dev components for the dotconf package.


%package doc
Summary: doc components for the dotconf package.
Group: Documentation

%description doc
doc components for the dotconf package.


%package lib
Summary: lib components for the dotconf package.
Group: Libraries
Requires: dotconf-license = %{version}-%{release}

%description lib
lib components for the dotconf package.


%package license
Summary: license components for the dotconf package.
Group: Default

%description license
license components for the dotconf package.


%prep
%setup -q -n dotconf-1.3
cd %{_builddir}/dotconf-1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1681404463
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1681404463
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dotconf
cp %{_builddir}/dotconf-%{version}/COPYING %{buildroot}/usr/share/package-licenses/dotconf/a738d98acac6c0d4d44d1a32420410908270bab2 || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/dotconf.h
/usr/lib64/libdotconf.so
/usr/lib64/pkgconfig/dotconf.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/dotconf/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdotconf.so.0
/usr/lib64/libdotconf.so.0.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dotconf/a738d98acac6c0d4d44d1a32420410908270bab2
